import {
  LayoutGrid,
  Snowflake,
  Utensils,
  Droplet,
  Package,
  Wheat,
  Tag,
  Sparkles,
} from "lucide-react"

export const fallbackCategories = [
  { icon: LayoutGrid, name: "New", href: "/products?sort=new" },
  { icon: Snowflake, name: "Ghee", href: "/products?category=ghee" },
  { icon: Utensils, name: "Oil", href: "/products?category=oil" },
  { icon: Droplet, name: "Deals", href: "/products?tag=deals" },
  { icon: Package, name: "Superfoods", href: "/products?category=superfoods" },
  { icon: Wheat, name: "Combo", href: "/products?category=combo" },
  { icon: Tag, name: "Under ₹499", href: "/products?price_lt=499" },
  { icon: Sparkles, name: "Under ₹999", href: "/products?price_lt=999" },
  { icon: LayoutGrid, name: "All", href: "/products" },
]

export const iconMap: Record<string, any> = {
  ghee: Snowflake,
  oils: Utensils,
  oil: Utensils,
  superfoods: Package,
  combo: Wheat,
  combos: Wheat,
  deals: Droplet,
  new: LayoutGrid,
  all: LayoutGrid,
}

export const fallbackProducts = [
  {
    id: 1,
    name: "Ghee Giants Combo - 5L + 5L",
    image: "/images/image.webp",
    price: 16653,
    originalPrice: 21350,
    rating: 4.8,
    reviews: 203,
    discount: "22% OFF",
    label: "Top Rated Choice",
    badgeType: "trending",
    weight: "10L",
    saveAmount: 4697,
  },
  {
    id: 2,
    name: "Khapli Atta 5 Kg Combo Pack of 2 - 5kg + 5kg",
    image: "/images/image.webp",
    price: 1547,
    originalPrice: 2200,
    rating: 4.7,
    reviews: 99,
    discount: "30% OFF",
    label: "Selling Fast",
    badgeType: "bolt",
    weight: "10kg",
    saveAmount: 653,
  },
  {
    id: 3,
    name: "A2 Gir Cow Ghee - 5L Dolchi",
    image: "/images/a2-ghee.webp",
    price: 10913,
    originalPrice: 11250,
    rating: 4.5,
    reviews: 673,
    discount: "3% OFF",
    label: "Top Rated Choice",
    bestSeller: true,
    badgeType: "trending",
    weight: "5L",
    saveAmount: 337,
  },
  {
    id: 4,
    name: "A2 Desi Cow Ghee - 5L Dolchi",
    image: "/images/a2-ghee.webp",
    price: 9797,
    originalPrice: 10100,
    rating: 4.7,
    reviews: 1382,
    discount: "3% OFF",
    label: "Top Rated Choice",
    bestSeller: true,
    badgeType: "trending",
    weight: "5L",
    saveAmount: 303,
  },
  {
    id: 5,
    name: "Bilona-Churned Desi Buffalo Ghee - 5L Dolchi",
    image: "/images/a2-ghee.webp",
    price: 6548,
    originalPrice: 6750,
    rating: 4.4,
    reviews: 202,
    discount: "3% OFF",
    label: "Top Rated Choice",
    bestSeller: true,
    badgeType: "trending",
    weight: "5L",
    saveAmount: 202,
  },
]
